export const Alert = () => import('../../modules/nuxt-uibox/ui/Alert.vue' /* webpackChunkName: "components/alert" */).then(c => wrapFunctional(c.default || c))
export const Button = () => import('../../modules/nuxt-uibox/ui/Button.vue' /* webpackChunkName: "components/button" */).then(c => wrapFunctional(c.default || c))
export const Content = () => import('../../modules/nuxt-uibox/ui/Content.vue' /* webpackChunkName: "components/content" */).then(c => wrapFunctional(c.default || c))
export const DropButton = () => import('../../modules/nuxt-uibox/ui/DropButton.vue' /* webpackChunkName: "components/drop-button" */).then(c => wrapFunctional(c.default || c))
export const Flex = () => import('../../modules/nuxt-uibox/ui/Flex.vue' /* webpackChunkName: "components/flex" */).then(c => wrapFunctional(c.default || c))
export const Grid = () => import('../../modules/nuxt-uibox/ui/Grid.vue' /* webpackChunkName: "components/grid" */).then(c => wrapFunctional(c.default || c))
export const Heading = () => import('../../modules/nuxt-uibox/ui/Heading.vue' /* webpackChunkName: "components/heading" */).then(c => wrapFunctional(c.default || c))
export const Hr = () => import('../../modules/nuxt-uibox/ui/Hr.vue' /* webpackChunkName: "components/hr" */).then(c => wrapFunctional(c.default || c))
export const Icon = () => import('../../modules/nuxt-uibox/ui/Icon.vue' /* webpackChunkName: "components/icon" */).then(c => wrapFunctional(c.default || c))
export const Img = () => import('../../modules/nuxt-uibox/ui/Img.vue' /* webpackChunkName: "components/img" */).then(c => wrapFunctional(c.default || c))
export const Input = () => import('../../modules/nuxt-uibox/ui/Input.vue' /* webpackChunkName: "components/input" */).then(c => wrapFunctional(c.default || c))
export const Label = () => import('../../modules/nuxt-uibox/ui/Label.vue' /* webpackChunkName: "components/label" */).then(c => wrapFunctional(c.default || c))
export const Li = () => import('../../modules/nuxt-uibox/ui/Li.vue' /* webpackChunkName: "components/li" */).then(c => wrapFunctional(c.default || c))
export const Loading = () => import('../../modules/nuxt-uibox/ui/Loading.vue' /* webpackChunkName: "components/loading" */).then(c => wrapFunctional(c.default || c))
export const Margin = () => import('../../modules/nuxt-uibox/ui/Margin.vue' /* webpackChunkName: "components/margin" */).then(c => wrapFunctional(c.default || c))
export const P = () => import('../../modules/nuxt-uibox/ui/P.vue' /* webpackChunkName: "components/p" */).then(c => wrapFunctional(c.default || c))
export const Padding = () => import('../../modules/nuxt-uibox/ui/Padding.vue' /* webpackChunkName: "components/padding" */).then(c => wrapFunctional(c.default || c))
export const Select = () => import('../../modules/nuxt-uibox/ui/Select.vue' /* webpackChunkName: "components/select" */).then(c => wrapFunctional(c.default || c))
export const Tab = () => import('../../modules/nuxt-uibox/ui/Tab.vue' /* webpackChunkName: "components/tab" */).then(c => wrapFunctional(c.default || c))
export const Textarea = () => import('../../modules/nuxt-uibox/ui/Textarea.vue' /* webpackChunkName: "components/textarea" */).then(c => wrapFunctional(c.default || c))
export const Ul = () => import('../../modules/nuxt-uibox/ui/Ul.vue' /* webpackChunkName: "components/ul" */).then(c => wrapFunctional(c.default || c))
export const IconsUilAngleDown = () => import('../../modules/nuxt-uibox/ui/Icons/uil-angle-down.vue' /* webpackChunkName: "components/icons-uil-angle-down" */).then(c => wrapFunctional(c.default || c))
export const IconsUilAngleLeftB = () => import('../../modules/nuxt-uibox/ui/Icons/uil-angle-left-b.vue' /* webpackChunkName: "components/icons-uil-angle-left-b" */).then(c => wrapFunctional(c.default || c))
export const IconsUilAngleLeft = () => import('../../modules/nuxt-uibox/ui/Icons/uil-angle-left.vue' /* webpackChunkName: "components/icons-uil-angle-left" */).then(c => wrapFunctional(c.default || c))
export const IconsUilAngleRightB = () => import('../../modules/nuxt-uibox/ui/Icons/uil-angle-right-b.vue' /* webpackChunkName: "components/icons-uil-angle-right-b" */).then(c => wrapFunctional(c.default || c))
export const IconsUilAngleRight = () => import('../../modules/nuxt-uibox/ui/Icons/uil-angle-right.vue' /* webpackChunkName: "components/icons-uil-angle-right" */).then(c => wrapFunctional(c.default || c))
export const IconsUilAngleUp = () => import('../../modules/nuxt-uibox/ui/Icons/uil-angle-up.vue' /* webpackChunkName: "components/icons-uil-angle-up" */).then(c => wrapFunctional(c.default || c))
export const IconsUilArrowDown = () => import('../../modules/nuxt-uibox/ui/Icons/uil-arrow-down.vue' /* webpackChunkName: "components/icons-uil-arrow-down" */).then(c => wrapFunctional(c.default || c))
export const IconsUilArrowLeft = () => import('../../modules/nuxt-uibox/ui/Icons/uil-arrow-left.vue' /* webpackChunkName: "components/icons-uil-arrow-left" */).then(c => wrapFunctional(c.default || c))
export const IconsUilArrowRight = () => import('../../modules/nuxt-uibox/ui/Icons/uil-arrow-right.vue' /* webpackChunkName: "components/icons-uil-arrow-right" */).then(c => wrapFunctional(c.default || c))
export const IconsUilArrowUp = () => import('../../modules/nuxt-uibox/ui/Icons/uil-arrow-up.vue' /* webpackChunkName: "components/icons-uil-arrow-up" */).then(c => wrapFunctional(c.default || c))
export const IconsUilAsterisk = () => import('../../modules/nuxt-uibox/ui/Icons/uil-asterisk.vue' /* webpackChunkName: "components/icons-uil-asterisk" */).then(c => wrapFunctional(c.default || c))
export const IconsUilBars = () => import('../../modules/nuxt-uibox/ui/Icons/uil-bars.vue' /* webpackChunkName: "components/icons-uil-bars" */).then(c => wrapFunctional(c.default || c))
export const IconsUilBellSlash = () => import('../../modules/nuxt-uibox/ui/Icons/uil-bell-slash.vue' /* webpackChunkName: "components/icons-uil-bell-slash" */).then(c => wrapFunctional(c.default || c))
export const IconsUilBell = () => import('../../modules/nuxt-uibox/ui/Icons/uil-bell.vue' /* webpackChunkName: "components/icons-uil-bell" */).then(c => wrapFunctional(c.default || c))
export const IconsUilBookOpen = () => import('../../modules/nuxt-uibox/ui/Icons/uil-book-open.vue' /* webpackChunkName: "components/icons-uil-book-open" */).then(c => wrapFunctional(c.default || c))
export const IconsUilBook = () => import('../../modules/nuxt-uibox/ui/Icons/uil-book.vue' /* webpackChunkName: "components/icons-uil-book" */).then(c => wrapFunctional(c.default || c))
export const IconsUilBox = () => import('../../modules/nuxt-uibox/ui/Icons/uil-box.vue' /* webpackChunkName: "components/icons-uil-box" */).then(c => wrapFunctional(c.default || c))
export const IconsUilBuilding = () => import('../../modules/nuxt-uibox/ui/Icons/uil-building.vue' /* webpackChunkName: "components/icons-uil-building" */).then(c => wrapFunctional(c.default || c))
export const IconsUilCalendarAlt = () => import('../../modules/nuxt-uibox/ui/Icons/uil-calendar-alt.vue' /* webpackChunkName: "components/icons-uil-calendar-alt" */).then(c => wrapFunctional(c.default || c))
export const IconsUilCalendarSlash = () => import('../../modules/nuxt-uibox/ui/Icons/uil-calendar-slash.vue' /* webpackChunkName: "components/icons-uil-calendar-slash" */).then(c => wrapFunctional(c.default || c))
export const IconsUilCameraPlus = () => import('../../modules/nuxt-uibox/ui/Icons/uil-camera-plus.vue' /* webpackChunkName: "components/icons-uil-camera-plus" */).then(c => wrapFunctional(c.default || c))
export const IconsUilCamera = () => import('../../modules/nuxt-uibox/ui/Icons/uil-camera.vue' /* webpackChunkName: "components/icons-uil-camera" */).then(c => wrapFunctional(c.default || c))
export const IconsUilChat = () => import('../../modules/nuxt-uibox/ui/Icons/uil-chat.vue' /* webpackChunkName: "components/icons-uil-chat" */).then(c => wrapFunctional(c.default || c))
export const IconsUilCheckCircle = () => import('../../modules/nuxt-uibox/ui/Icons/uil-check-circle.vue' /* webpackChunkName: "components/icons-uil-check-circle" */).then(c => wrapFunctional(c.default || c))
export const IconsUilCheckSquare = () => import('../../modules/nuxt-uibox/ui/Icons/uil-check-square.vue' /* webpackChunkName: "components/icons-uil-check-square" */).then(c => wrapFunctional(c.default || c))
export const IconsUilClipboardNotes = () => import('../../modules/nuxt-uibox/ui/Icons/uil-clipboard-notes.vue' /* webpackChunkName: "components/icons-uil-clipboard-notes" */).then(c => wrapFunctional(c.default || c))
export const IconsUilCloudUpload = () => import('../../modules/nuxt-uibox/ui/Icons/uil-cloud-upload.vue' /* webpackChunkName: "components/icons-uil-cloud-upload" */).then(c => wrapFunctional(c.default || c))
export const IconsUilCommentAltMessage = () => import('../../modules/nuxt-uibox/ui/Icons/uil-comment-alt-message.vue' /* webpackChunkName: "components/icons-uil-comment-alt-message" */).then(c => wrapFunctional(c.default || c))
export const IconsUilConfused = () => import('../../modules/nuxt-uibox/ui/Icons/uil-confused.vue' /* webpackChunkName: "components/icons-uil-confused" */).then(c => wrapFunctional(c.default || c))
export const IconsUilCopy = () => import('../../modules/nuxt-uibox/ui/Icons/uil-copy.vue' /* webpackChunkName: "components/icons-uil-copy" */).then(c => wrapFunctional(c.default || c))
export const IconsUilCreditCard = () => import('../../modules/nuxt-uibox/ui/Icons/uil-credit-card.vue' /* webpackChunkName: "components/icons-uil-credit-card" */).then(c => wrapFunctional(c.default || c))
export const IconsUilDiscord = () => import('../../modules/nuxt-uibox/ui/Icons/uil-discord.vue' /* webpackChunkName: "components/icons-uil-discord" */).then(c => wrapFunctional(c.default || c))
export const IconsUilEnvelopeAlt = () => import('../../modules/nuxt-uibox/ui/Icons/uil-envelope-alt.vue' /* webpackChunkName: "components/icons-uil-envelope-alt" */).then(c => wrapFunctional(c.default || c))
export const IconsUilEnvelopeTimes = () => import('../../modules/nuxt-uibox/ui/Icons/uil-envelope-times.vue' /* webpackChunkName: "components/icons-uil-envelope-times" */).then(c => wrapFunctional(c.default || c))
export const IconsUilEnvelopeUpload = () => import('../../modules/nuxt-uibox/ui/Icons/uil-envelope-upload.vue' /* webpackChunkName: "components/icons-uil-envelope-upload" */).then(c => wrapFunctional(c.default || c))
export const IconsUilEnvelope = () => import('../../modules/nuxt-uibox/ui/Icons/uil-envelope.vue' /* webpackChunkName: "components/icons-uil-envelope" */).then(c => wrapFunctional(c.default || c))
export const IconsUilEstate = () => import('../../modules/nuxt-uibox/ui/Icons/uil-estate.vue' /* webpackChunkName: "components/icons-uil-estate" */).then(c => wrapFunctional(c.default || c))
export const IconsUilExclamationOctagon = () => import('../../modules/nuxt-uibox/ui/Icons/uil-exclamation-octagon.vue' /* webpackChunkName: "components/icons-uil-exclamation-octagon" */).then(c => wrapFunctional(c.default || c))
export const IconsUilExclamationTriangle = () => import('../../modules/nuxt-uibox/ui/Icons/uil-exclamation-triangle.vue' /* webpackChunkName: "components/icons-uil-exclamation-triangle" */).then(c => wrapFunctional(c.default || c))
export const IconsUilEyeSlash = () => import('../../modules/nuxt-uibox/ui/Icons/uil-eye-slash.vue' /* webpackChunkName: "components/icons-uil-eye-slash" */).then(c => wrapFunctional(c.default || c))
export const IconsUilEye = () => import('../../modules/nuxt-uibox/ui/Icons/uil-eye.vue' /* webpackChunkName: "components/icons-uil-eye" */).then(c => wrapFunctional(c.default || c))
export const IconsUilFacebookF = () => import('../../modules/nuxt-uibox/ui/Icons/uil-facebook-f.vue' /* webpackChunkName: "components/icons-uil-facebook-f" */).then(c => wrapFunctional(c.default || c))
export const IconsUilFacebook = () => import('../../modules/nuxt-uibox/ui/Icons/uil-facebook.vue' /* webpackChunkName: "components/icons-uil-facebook" */).then(c => wrapFunctional(c.default || c))
export const IconsUilFileEditAlt = () => import('../../modules/nuxt-uibox/ui/Icons/uil-file-edit-alt.vue' /* webpackChunkName: "components/icons-uil-file-edit-alt" */).then(c => wrapFunctional(c.default || c))
export const IconsUilFilterSlash = () => import('../../modules/nuxt-uibox/ui/Icons/uil-filter-slash.vue' /* webpackChunkName: "components/icons-uil-filter-slash" */).then(c => wrapFunctional(c.default || c))
export const IconsUilFilter = () => import('../../modules/nuxt-uibox/ui/Icons/uil-filter.vue' /* webpackChunkName: "components/icons-uil-filter" */).then(c => wrapFunctional(c.default || c))
export const IconsUilGripHorizontalLine = () => import('../../modules/nuxt-uibox/ui/Icons/uil-grip-horizontal-line.vue' /* webpackChunkName: "components/icons-uil-grip-horizontal-line" */).then(c => wrapFunctional(c.default || c))
export const IconsUilHunting = () => import('../../modules/nuxt-uibox/ui/Icons/uil-hunting.vue' /* webpackChunkName: "components/icons-uil-hunting" */).then(c => wrapFunctional(c.default || c))
export const IconsUilImagePlus = () => import('../../modules/nuxt-uibox/ui/Icons/uil-image-plus.vue' /* webpackChunkName: "components/icons-uil-image-plus" */).then(c => wrapFunctional(c.default || c))
export const IconsUilImageUpload = () => import('../../modules/nuxt-uibox/ui/Icons/uil-image-upload.vue' /* webpackChunkName: "components/icons-uil-image-upload" */).then(c => wrapFunctional(c.default || c))
export const IconsUilImage = () => import('../../modules/nuxt-uibox/ui/Icons/uil-image.vue' /* webpackChunkName: "components/icons-uil-image" */).then(c => wrapFunctional(c.default || c))
export const IconsUilInfoCircle = () => import('../../modules/nuxt-uibox/ui/Icons/uil-info-circle.vue' /* webpackChunkName: "components/icons-uil-info-circle" */).then(c => wrapFunctional(c.default || c))
export const IconsUilInstagramAlt = () => import('../../modules/nuxt-uibox/ui/Icons/uil-instagram-alt.vue' /* webpackChunkName: "components/icons-uil-instagram-alt" */).then(c => wrapFunctional(c.default || c))
export const IconsUilInstagram = () => import('../../modules/nuxt-uibox/ui/Icons/uil-instagram.vue' /* webpackChunkName: "components/icons-uil-instagram" */).then(c => wrapFunctional(c.default || c))
export const IconsUilLayersSlash = () => import('../../modules/nuxt-uibox/ui/Icons/uil-layers-slash.vue' /* webpackChunkName: "components/icons-uil-layers-slash" */).then(c => wrapFunctional(c.default || c))
export const IconsUilLayers = () => import('../../modules/nuxt-uibox/ui/Icons/uil-layers.vue' /* webpackChunkName: "components/icons-uil-layers" */).then(c => wrapFunctional(c.default || c))
export const IconsUilLetterEnglishA = () => import('../../modules/nuxt-uibox/ui/Icons/uil-letter-english-a.vue' /* webpackChunkName: "components/icons-uil-letter-english-a" */).then(c => wrapFunctional(c.default || c))
export const IconsUilLinkAlt = () => import('../../modules/nuxt-uibox/ui/Icons/uil-link-alt.vue' /* webpackChunkName: "components/icons-uil-link-alt" */).then(c => wrapFunctional(c.default || c))
export const IconsUilLinkH = () => import('../../modules/nuxt-uibox/ui/Icons/uil-link-h.vue' /* webpackChunkName: "components/icons-uil-link-h" */).then(c => wrapFunctional(c.default || c))
export const IconsUilLocationPinAlt = () => import('../../modules/nuxt-uibox/ui/Icons/uil-location-pin-alt.vue' /* webpackChunkName: "components/icons-uil-location-pin-alt" */).then(c => wrapFunctional(c.default || c))
export const IconsUilLock = () => import('../../modules/nuxt-uibox/ui/Icons/uil-lock.vue' /* webpackChunkName: "components/icons-uil-lock" */).then(c => wrapFunctional(c.default || c))
export const IconsUilMapMarkerSlash = () => import('../../modules/nuxt-uibox/ui/Icons/uil-map-marker-slash.vue' /* webpackChunkName: "components/icons-uil-map-marker-slash" */).then(c => wrapFunctional(c.default || c))
export const IconsUilMapPin = () => import('../../modules/nuxt-uibox/ui/Icons/uil-map-pin.vue' /* webpackChunkName: "components/icons-uil-map-pin" */).then(c => wrapFunctional(c.default || c))
export const IconsUilMegaphone = () => import('../../modules/nuxt-uibox/ui/Icons/uil-megaphone.vue' /* webpackChunkName: "components/icons-uil-megaphone" */).then(c => wrapFunctional(c.default || c))
export const IconsUilMinus = () => import('../../modules/nuxt-uibox/ui/Icons/uil-minus.vue' /* webpackChunkName: "components/icons-uil-minus" */).then(c => wrapFunctional(c.default || c))
export const IconsUilOutgoingCall = () => import('../../modules/nuxt-uibox/ui/Icons/uil-outgoing-call.vue' /* webpackChunkName: "components/icons-uil-outgoing-call" */).then(c => wrapFunctional(c.default || c))
export const IconsUilPhone = () => import('../../modules/nuxt-uibox/ui/Icons/uil-phone.vue' /* webpackChunkName: "components/icons-uil-phone" */).then(c => wrapFunctional(c.default || c))
export const IconsUilPlus = () => import('../../modules/nuxt-uibox/ui/Icons/uil-plus.vue' /* webpackChunkName: "components/icons-uil-plus" */).then(c => wrapFunctional(c.default || c))
export const IconsUilQuestionCircle = () => import('../../modules/nuxt-uibox/ui/Icons/uil-question-circle.vue' /* webpackChunkName: "components/icons-uil-question-circle" */).then(c => wrapFunctional(c.default || c))
export const IconsUilRedditAlienAlt = () => import('../../modules/nuxt-uibox/ui/Icons/uil-reddit-alien-alt.vue' /* webpackChunkName: "components/icons-uil-reddit-alien-alt" */).then(c => wrapFunctional(c.default || c))
export const IconsUilRestaurant = () => import('../../modules/nuxt-uibox/ui/Icons/uil-restaurant.vue' /* webpackChunkName: "components/icons-uil-restaurant" */).then(c => wrapFunctional(c.default || c))
export const IconsUilSearchMinus = () => import('../../modules/nuxt-uibox/ui/Icons/uil-search-minus.vue' /* webpackChunkName: "components/icons-uil-search-minus" */).then(c => wrapFunctional(c.default || c))
export const IconsUilSearchPlus = () => import('../../modules/nuxt-uibox/ui/Icons/uil-search-plus.vue' /* webpackChunkName: "components/icons-uil-search-plus" */).then(c => wrapFunctional(c.default || c))
export const IconsUilSearch = () => import('../../modules/nuxt-uibox/ui/Icons/uil-search.vue' /* webpackChunkName: "components/icons-uil-search" */).then(c => wrapFunctional(c.default || c))
export const IconsUilSetting = () => import('../../modules/nuxt-uibox/ui/Icons/uil-setting.vue' /* webpackChunkName: "components/icons-uil-setting" */).then(c => wrapFunctional(c.default || c))
export const IconsUilShareAlt = () => import('../../modules/nuxt-uibox/ui/Icons/uil-share-alt.vue' /* webpackChunkName: "components/icons-uil-share-alt" */).then(c => wrapFunctional(c.default || c))
export const IconsUilShoppingBag = () => import('../../modules/nuxt-uibox/ui/Icons/uil-shopping-bag.vue' /* webpackChunkName: "components/icons-uil-shopping-bag" */).then(c => wrapFunctional(c.default || c))
export const IconsUilShoppingCart = () => import('../../modules/nuxt-uibox/ui/Icons/uil-shopping-cart.vue' /* webpackChunkName: "components/icons-uil-shopping-cart" */).then(c => wrapFunctional(c.default || c))
export const IconsUilSignout = () => import('../../modules/nuxt-uibox/ui/Icons/uil-signout.vue' /* webpackChunkName: "components/icons-uil-signout" */).then(c => wrapFunctional(c.default || c))
export const IconsUilSquareFull = () => import('../../modules/nuxt-uibox/ui/Icons/uil-square-full.vue' /* webpackChunkName: "components/icons-uil-square-full" */).then(c => wrapFunctional(c.default || c))
export const IconsUilSquare = () => import('../../modules/nuxt-uibox/ui/Icons/uil-square.vue' /* webpackChunkName: "components/icons-uil-square" */).then(c => wrapFunctional(c.default || c))
export const IconsUilStoreAlt = () => import('../../modules/nuxt-uibox/ui/Icons/uil-store-alt.vue' /* webpackChunkName: "components/icons-uil-store-alt" */).then(c => wrapFunctional(c.default || c))
export const IconsUilSuitcase = () => import('../../modules/nuxt-uibox/ui/Icons/uil-suitcase.vue' /* webpackChunkName: "components/icons-uil-suitcase" */).then(c => wrapFunctional(c.default || c))
export const IconsUilTablet = () => import('../../modules/nuxt-uibox/ui/Icons/uil-tablet.vue' /* webpackChunkName: "components/icons-uil-tablet" */).then(c => wrapFunctional(c.default || c))
export const IconsUilTelegramAlt = () => import('../../modules/nuxt-uibox/ui/Icons/uil-telegram-alt.vue' /* webpackChunkName: "components/icons-uil-telegram-alt" */).then(c => wrapFunctional(c.default || c))
export const IconsUilTimes = () => import('../../modules/nuxt-uibox/ui/Icons/uil-times.vue' /* webpackChunkName: "components/icons-uil-times" */).then(c => wrapFunctional(c.default || c))
export const IconsUilTrashAlt = () => import('../../modules/nuxt-uibox/ui/Icons/uil-trash-alt.vue' /* webpackChunkName: "components/icons-uil-trash-alt" */).then(c => wrapFunctional(c.default || c))
export const IconsUilTrash = () => import('../../modules/nuxt-uibox/ui/Icons/uil-trash.vue' /* webpackChunkName: "components/icons-uil-trash" */).then(c => wrapFunctional(c.default || c))
export const IconsUilTwitterAlt = () => import('../../modules/nuxt-uibox/ui/Icons/uil-twitter-alt.vue' /* webpackChunkName: "components/icons-uil-twitter-alt" */).then(c => wrapFunctional(c.default || c))
export const IconsUilTwitter = () => import('../../modules/nuxt-uibox/ui/Icons/uil-twitter.vue' /* webpackChunkName: "components/icons-uil-twitter" */).then(c => wrapFunctional(c.default || c))
export const IconsUilUploadAlt = () => import('../../modules/nuxt-uibox/ui/Icons/uil-upload-alt.vue' /* webpackChunkName: "components/icons-uil-upload-alt" */).then(c => wrapFunctional(c.default || c))
export const IconsUilUpload = () => import('../../modules/nuxt-uibox/ui/Icons/uil-upload.vue' /* webpackChunkName: "components/icons-uil-upload" */).then(c => wrapFunctional(c.default || c))
export const IconsUilUserCheck = () => import('../../modules/nuxt-uibox/ui/Icons/uil-user-check.vue' /* webpackChunkName: "components/icons-uil-user-check" */).then(c => wrapFunctional(c.default || c))
export const IconsUilUserCircle = () => import('../../modules/nuxt-uibox/ui/Icons/uil-user-circle.vue' /* webpackChunkName: "components/icons-uil-user-circle" */).then(c => wrapFunctional(c.default || c))
export const IconsUilUser = () => import('../../modules/nuxt-uibox/ui/Icons/uil-user.vue' /* webpackChunkName: "components/icons-uil-user" */).then(c => wrapFunctional(c.default || c))
export const IconsUilWhatsappAlt = () => import('../../modules/nuxt-uibox/ui/Icons/uil-whatsapp-alt.vue' /* webpackChunkName: "components/icons-uil-whatsapp-alt" */).then(c => wrapFunctional(c.default || c))
export const IconsUilWhatsapp = () => import('../../modules/nuxt-uibox/ui/Icons/uil-whatsapp.vue' /* webpackChunkName: "components/icons-uil-whatsapp" */).then(c => wrapFunctional(c.default || c))
export const IconsUilYoutube = () => import('../../modules/nuxt-uibox/ui/Icons/uil-youtube.vue' /* webpackChunkName: "components/icons-uil-youtube" */).then(c => wrapFunctional(c.default || c))
export const NoResults = () => import('../../components/Elements/NoResults.vue' /* webpackChunkName: "components/no-results" */).then(c => wrapFunctional(c.default || c))
export const Footer = () => import('../../components/Footer.vue' /* webpackChunkName: "components/footer" */).then(c => wrapFunctional(c.default || c))
export const Header = () => import('../../components/Header.vue' /* webpackChunkName: "components/header" */).then(c => wrapFunctional(c.default || c))
export const FacturaActions = () => import('../../components/Factura/Actions.vue' /* webpackChunkName: "components/factura-actions" */).then(c => wrapFunctional(c.default || c))
export const FacturaData = () => import('../../components/Factura/Data.vue' /* webpackChunkName: "components/factura-data" */).then(c => wrapFunctional(c.default || c))
export const FacturaHeader = () => import('../../components/Factura/Header.vue' /* webpackChunkName: "components/factura-header" */).then(c => wrapFunctional(c.default || c))

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
