name: Build and deploy
on:
  push:
    paths-ignore:
    - 'assets/**'
    - 'components/**'
    - 'hooks/**'
    - 'layouts/**'
    - 'middleware/**'
    - 'modules/**'
    - 'pages/**'
    - 'plugins/**'
    - 'server/**'
    - 'static/**'
    - 'store/**'
    - '.editorconfig'
    - '.gitignore'
    - 'ecosystem.config.js'
    - 'nuxt.config.js'
    - 'README.md'
    branches:
    - dev
jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    steps:
      - name: Configurando node v16
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
      - name: Accediendo al flujo de trabajo
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Instalando dependencias
        run: yarn
      - name: Sleep 5
        run: sleep 5
      - name: Compilando
        run: yarn build
      - name: Sleep 10
        run: sleep 10
      - name: Copiando a la rama main
        uses: planetoftheweb/copy-to-branches@v1
        env:
          branches: main
          key: dev
          files: config server static store nuxt.config.js package.json .nuxt
      - name: ls
        run: ls
